name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Set up the required Node.js version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Ensure Node.js 20 is used

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the app
      - name: Build the app
        run: npm run build

      # Deploy to Azure Static Web Apps
      - name: Deploy to Azure
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_GLACIER_065A44203 }}
          action: "upload"
          app_location: "src" # Path to your app source code
          api_location: "api" # Path to your API code (if applicable)
          output_location: "build" # Path to the app build output directory

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
